permalink: /posts/:title
permalink: /projects/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Reakain Blep
url: https://zachholman.com/left
description: A fantastic blog that is fantastic.
twitter: the_reakain
